---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-ops-view.fullname" . }}
  labels:
    {{- include "kube-ops-view.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-ops-view.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-ops-view.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-ops-view.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.args .Values.redis.enabled }}
          args:
            {{- if .Values.redis.enabled }}
            - --redis-url=redis://{{ .Release.Name }}-redis-master:6379
            {{- end }}
            {{- with .Values.args }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if and .Values.ingress.enabled .Values.ingress.oauth.enabled }}
          env:
            - name: APP_URL
              {{- with (index .Values.ingress.hosts 0) }}
              value: https://{{ .host }}
              {{- end }}
            - name: AUTHORIZE_URL
              value: {{ .Values.ingress.oauth.authorizeUrl }}
            - name: ACCESS_TOKEN_URL
              value: {{ .Values.ingress.oauth.accessTokenUrl }}
            - name: CREDENTIALS_DIR
              value: /oidc-credentials
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.ingress.oauth.enabled }}
          volumeMounts:
            - name: oidc-credentials
              mountPath: /oidc-credentials
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.ingress.oauth.enabled }}
      volumes:
        - name: oidc-credentials
          configMap:
            name: {{ include "kube-ops-view.fullname" . }}-oidc
      {{- end }}
